### ISSUE TITLE
crash when trying to load a config in-game

### ISSUE THREAD

**Issue by crwn1337** [nullworks/cathook#690] opened 2019-02-20 16:39 UTC
**Describe the Bug**
trying to load a config in-game will result in a crash

**To Reproduce**
1. inject cathook
2. go in to any server
3. try to load a config in-game
4. crash

**Expected behavior**
no crash

**Logs**
[cathook-kasutaja-7312-segfault.log](https://github.com/nullworks/cathook/files/2885558/cathook-kasutaja-7312-segfault.log)

**Comment by BenCat07** [comment] 2019-02-20 16:47
I cannot reproduce the crash nor do i know what is causing it, all i see id tf2 related addresses inside the backtrace, sorry

**Comment by ItzNop** [comment] 2019-02-20 16:50
its really weird, sometimes it doesnt crash and sometimes i have to play 30~2 hours before loading a config crashes the game

**Comment by crwn1337** [comment] 2019-02-24 20:11
reinstalling arch fixed this for some reason

**Comment by TotallyNotElite** [comment] 2019-02-24 20:12
Ok thanks //closing

**Closed by TotallyNotElite** 2019-02-24 20:12 UTC
Labels: crash, need more info, p:high
