### ISSUE TITLE
[Request] Exclusive option to have projectile weapons aim only at the feet.

### ISSUE THREAD

**Issue by totallynotspook** [nullworks/cathook#994] opened 2020-05-06 18:14 UTC
While setting in aimbot settings the aimbot to static and to aim at either right or left feet works, it also forces the shotgun to aim only at the feet, I know auto/auto-closest can be used as well but just a suggestion.

**Comment by TotallyNotElite** [comment] 2020-05-06 18:15
Duplicate of #750, if you disagree then just tell me here

**Closed by TotallyNotElite** 2020-05-06 18:15 UTC

**Comment by BenCat07** [comment] 2020-05-06 18:19
they already aim at the feet, if the enemy is on ground that is, else it shoots at hip
