### ISSUE TITLE
Show Toggle status under label

### ISSUE THREAD

**Issue by SylveonBottle** [nullworks/cathook#762] opened 2019-06-20 15:56 UTC
If user has aimbot/triggerbot/etc set to TOGGLE, display "Aimbot Enabled"(/etc) underneath cathook logo.

**Comment by Retarded-Skid** [comment] 2019-06-21 23:09
We were playing yesterday and I would lose track of some of the hacks I had on toggle and what their status was. A simple list showing what is toggled on would be very helpful for people with bad memory like me.

**Comment by TotallyNotElite** [comment] 2019-10-23 16:25
I consider this to be a duplicate of #164

**Closed by TotallyNotElite** 2019-10-23 16:25 UTC
