### ISSUE TITLE
fail to compile

### ISSUE THREAD

**Issue by moderfuk** [nullworks/cathook#1187] opened 2020-12-02 16:43 UTC
It fails to compile on ubuntu ./scripts/migrations: line 57: curl: command not found
HEAD is now at 0a0f9ca Remove /tmp/dumps chmod
~/Desktop/public/public/cathook/build ~/Desktop/public/public/cathook
-- The C compiler identification is GNU 7.5.0
-- The CXX compiler identification is GNU 7.5.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- broken
CMake Error at /usr/share/cmake-3.16/Modules/CMakeTestCCompiler.cmake:60 (message):
  The C compiler

    "/usr/bin/cc"

  is not able to compile a simple test program.

  It fails with the following output:

    Change Dir: /home/noid/Desktop/public/public/cathook/build/CMakeFiles/CMakeTmp
    
    Run Build Command(s):/usr/bin/make cmTC_03842/fast && /usr/bin/make -f CMakeFiles/cmTC_03842.dir/build.make CMakeFiles/cmTC_03842.dir/build
    make[1]: Entering directory '/home/noid/Desktop/public/public/cathook/build/CMakeFiles/CMakeTmp'
    Building C object CMakeFiles/cmTC_03842.dir/testCCompiler.c.o
    /usr/bin/cc   -m32    -o CMakeFiles/cmTC_03842.dir/testCCompiler.c.o   -c /home/noid/Desktop/public/public/cathook/build/CMakeFiles/CMakeTmp/testCCompiler.c
    Linking C executable cmTC_03842
    /usr/bin/cmake -E cmake_link_script CMakeFiles/cmTC_03842.dir/link.txt --verbose=1
    /usr/bin/cc -m32   -m32 -L/usr/lib32  CMakeFiles/cmTC_03842.dir/testCCompiler.c.o  -o cmTC_03842 
    /usr/bin/ld: skipping incompatible /usr/lib/gcc/x86_64-linux-gnu/7/libgcc.a when searching for -lgcc
    /usr/bin/ld: cannot find -lgcc
    /usr/bin/ld: skipping incompatible /usr/lib/gcc/x86_64-linux-gnu/7/libgcc.a when searching for -lgcc
    /usr/bin/ld: cannot find -lgcc
    collect2: error: ld returned 1 exit status
    make[1]: *** [CMakeFiles/cmTC_03842.dir/build.make:87: cmTC_03842] Error 1
    make[1]: Leaving directory '/home/noid/Desktop/public/public/cathook/build/CMakeFiles/CMakeTmp'
    make: *** [Makefile:121: cmTC_03842/fast] Error 2
    
    

  

  CMake will not be able to correctly generate this project.
Call Stack (most recent call first):
  CMakeLists.txt:45 (project)

-- Configuring incomplete, errors occurred!
See also "/home/noid/Desktop/public/public/cathook/build/CMakeFiles/CMakeOutput.log".
See also "/home/noid/Desktop/public/public/cathook/build/CMakeFiles/CMakeError.log".
 
 
Failed to compile cathook

**Comment by TotallyNotElite** [comment] 2020-12-02 16:45
I don't get how the fuck this happened. What ubuntu version/flavour is this?

**Comment by moderfuk** [comment] 2020-12-02 16:47
> I don't get how the fuck this happened. What ubuntu version/flavour is this?

ver 20.04.1lts

**Comment by BenCat07** [comment] 2020-12-17 10:13
If it isnt able to compile a simple test program, something about your system is broken

**Comment by iraizo** [comment] 2021-03-28 20:03
Installing `libtool` should fix this.

**Comment by TotallyNotElite** [comment] 2021-03-28 20:04
In that case it is our bug, since Ubuntu Linux is an officially supported distro. If someone can reproduce this issue and confirm libtool is at fault, then we can add it to `scripts/dependencycheck`

**Comment by iraizo** [comment] 2021-03-28 20:07
> In that case it is our bug, since Ubuntu Linux is an officially supported distro. If someone can reproduce this issue and confirm libtool is at fault, then we can add it to `scripts/dependencycheck`

I needed to compile something with `rustc` on a ubuntu server and fixed it like that ([stackoverflow link](https://stackoverflow.com/questions/335928/ld-cannot-find-an-existing-library)) so it should probaly be added to the dependecy check

**Comment by TotallyNotElite** [comment] 2021-03-28 20:09
That does not look like it's relevant here, just looks like the person is missing 32 bit libgcc.

**Comment by iraizo** [comment] 2021-03-28 20:11
libgcc could also be it, yeah

**Comment by Trapacid** [comment] 2021-03-28 21:34
Can't confirm this bug exists. 
I whipped up a quick Ubuntu 20.04.2 LTS virtual machine, installed nothing but git, then cloned and ran the `install-all` script. Compiled successfully.

OP seems to have an incorrect libgcc version as I happen to have `/usr/lib/gcc/x86_64-linux-gnu/9/` after running the script, which OP has `7`. 

I can't think of a possible way how they ended up with only 7 and not 9 after running the dependencycheck script because I manually installed libgcc-7-dev, purged all these packages (`build-essential git g++ g++-multilib libboost-dev gdb libsdl2-dev:i386 libfreetype6-dev:i386 cmake dialog rsync`), reinstalled them, and I still ended up with libgcc-9-dev being installed as a dependency.

If you really want, you can add `libgcc-9-dev` to the dependencycheck script, but one of those packages **should** already come with it like I demonstrated.

**Comment by TotallyNotElite** [comment] 2021-03-28 21:35
I think we're just gonna put this down as "wontfix" and call it a day, thanks for your work @Trapacid :)

**Closed** 2021-03-28 21:35 UTC
Labels: d:easy, invalid, not our bug, wontfix
