### ISSUE TITLE
[Crash] On new manjaro install. 

### ISSUE THREAD

**Issue by iraizo** [nullworks/cathook#1344] opened 2021-02-09 23:47 UTC
> > @BenCat07 Does this look good? I cant really test it since cathook is now crashing on every install.
> 
> hold up, what

Yeah, reinstalled manjaro using a stable kernel and im still crashing. 
`warning: Could not load shared library symbols for bin/launcher.so.
Do you need "set solib-search-path" or "set sysroot"?
Error while reading shared library symbols for /usr/lib32/libpthread.so.0:
Cannot find user-level thread for LWP 3076: generic error
0xf7f82549 in __kernel_vsyscall ()
Calling dlopen
Cannot find user-level thread for LWP 3430: generic error
An error occurred while in a function called from GDB.
Evaluation of the expression containing the function
(dlopen) will be abandoned.
When the function is done executing, GDB will silently stop.
Calling dlerror
Selected thread is running.
./attach: line 45:  3393 Aborted                 (core dumped) gdb -n -q -batch -ex "attach $proc" -ex "echo \033[1mCalling dlopen\033[0m\n" -ex "call ((void()(const char, int))dlopen)("$FILENAME", 1)" -ex "echo \033[1mCalling dlerror\033[0m\n" -ex "call ((char(*)(void))dlerror)()" -ex "detach" -ex "quit"`
 or are you refering to the code?

_Originally posted by @iraizo in https://github.com/nullworks/cathook/issues/1341#issuecomment-776069328_

**Comment by Wristing** [comment] 2021-02-10 11:25
im on arch and when i updated my system i got this issue too

warning: Could not load shared library symbols for bin/launcher.so.
Do you need "set solib-search-path" or "set sysroot"?
Error while reading shared library symbols for /usr/lib32/libpthread.so.0:
Cannot find user-level thread for LWP 13459: generic error
0xf7f5a549 in __kernel_vsyscall ()
Calling dlopen
Cannot find user-level thread for LWP 14184: generic error
An error occurred while in a function called from GDB.
Evaluation of the expression containing the function
(dlopen) will be abandoned.
When the function is done executing, GDB will silently stop.
Calling dlerror
Selected thread is running.
./attach: line 45: 14069 Aborted                 (core dumped) gdb -n -q -batch -ex "attach $proc" -ex "echo \033[1mCalling dlopen\033[0m\n" -ex "call ((void*(*)(const char*, int))dlopen)(\"$FILENAME\", 1)" -ex "echo \033[1mCalling dlerror\033[0m\n" -ex "call ((char*(*)(void))dlerror)()" -ex "detach" -ex "quit"

**Comment by Trapacid** [comment] 2021-02-11 01:30
Same issue on Garuda Linux (Arch-based):

```
Running instances: 914957
Attaching to 914957
loading /tmp/.glwDTgb3 to 914957
[New LWP 914958]
[New LWP 914960]
[New LWP 915150]
[New LWP 915151]
[New LWP 915586]
[New LWP 915587]
[New LWP 915588]
[New LWP 915589]
[New LWP 915849]
[New LWP 915850]
[New LWP 915851]
[New LWP 915852]
[New LWP 915853]
[New LWP 915854]
[New LWP 915855]
[New LWP 915857]
[New LWP 915860]
warning: Could not load shared library symbols for bin/launcher.so.
Do you need "set solib-search-path" or "set sysroot"?
Error while reading shared library symbols for /usr/lib32/libpthread.so.0:
Cannot find user-level thread for LWP 915860: generic error
0xf7f70549 in __kernel_vsyscall ()
Calling dlopen
Cannot find user-level thread for LWP 923347: generic error
An error occurred while in a function called from GDB.
Evaluation of the expression containing the function
(dlopen) will be abandoned.
When the function is done executing, GDB will silently stop.
Calling dlerror
Selected thread is running.
./attach: line 45: 923319 Aborted                 (core dumped) gdb -n -q -batch -ex "attach $proc" -ex "echo \033[1mCalling dlopen\033[0m\n" -ex "call ((void*(*)(const char*, int))dlopen)(\"$FILENAME\", 1)" -ex "echo \033[1mCalling dlerror\033[0m\n" -ex "call ((char*(*)(void))dlerror)()" -ex "detach" -ex "quit"```

**Comment by iraizo** [comment] 2021-02-11 15:42
getting the same crash.

**Comment by BenCat07** [comment] 2021-02-11 15:43
Identified to be a **manjaro bug**. I made a forum post already, detailing the issue.

https://forum.manjaro.org/t/critical-bug-gdb-broken-with-last-stable-update/53155/2

**Comment by iraizo** [comment] 2021-02-11 15:52
> Identified to be a **manjaro bug**. I made a forum post already, detailing the issue.
> 
> https://forum.manjaro.org/t/critical-bug-gdb-broken-with-last-stable-update/53155

That seems like a upstream issue and not a manjaro bug, because this is happening not only on manjaro but also Garuda Linux and both of them are arch based.

**Comment by BenCat07** [comment] 2021-02-11 16:15
I am not sure, but it does occur in manjaro since stable update

**Comment by dweee** [comment] 2021-02-11 18:28
Some people over at LWSS/Fuzion#621 are also having issues seems like compiling and loading the library through LD_PRELOAD works though at least for CS.

**Comment by TotallyNotElite** [comment] 2021-02-11 18:29
Well I already know an actual workaround for this that does not require preloading. Cathook's preload script works as intended if you have steam-native/steam-native-runtime installed.

**Comment by TotallyNotElite** [comment] 2021-02-11 18:50
Ok rebuilding GDB does not solve it, that's for sure now.

**Comment by TotallyNotElite** [comment] 2021-02-11 20:40
Fixed in https://github.com/nullworks/cathook/pull/1347/commits/0ad305f5ebe96103d0ae775c120209d5d910652b

**Comment by TotallyNotElite** [comment] 2021-02-11 20:58
Tfw you're trying to fix a p:high issue, but no maintainer is available to sign off on your pull request

**Comment by iraizo** [comment] 2021-02-11 21:20
> Fixed in [0ad305f](https://github.com/nullworks/cathook/commit/0ad305f5ebe96103d0ae775c120209d5d910652b)

Pulled and getting `
Running instances: 1779446
Attaching to 1779446
loading /tmp/.glnTzhGr to 1779446
[New LWP 1779550]
[New LWP 1779552]
[New LWP 1779554]
[New LWP 1779555]
[New LWP 1780759]
[New LWP 1780761]
[New LWP 1781075]
[New LWP 1781076]
[New LWP 1781077]
[New LWP 1781078]
[New LWP 1781472]
[New LWP 1781473]
[New LWP 1781474]
[New LWP 1781475]
[New LWP 1781476]
[New LWP 1781477]
[New LWP 1781481]
warning: Could not load shared library symbols for bin/launcher.so.
Do you need "set solib-search-path" or "set sysroot"?
Error while reading shared library symbols for /usr/lib32/libpthread.so.0:
Cannot find user-level thread for LWP 1781481: generic error
0xf7f88549 in __kernel_vsyscall ()
Calling dlopen
Cannot find user-level thread for LWP 1782567: generic error
An error occurred while in a function called from GDB.
Evaluation of the expression containing the function
(dlopen) will be abandoned.
When the function is done executing, GDB will silently stop.
Calling dlerror
Selected thread is running.
./attach: line 50: 1782524 Aborted                 (core dumped) $gdbbin -n -q -batch -ex "attach $proc" -ex "echo \033[1mCalling dlopen\033[0m\n" -ex "call ((void*(*)(const char*, int))dlopen)(\"$FILENAME\", 1)" -ex "echo \033[1mCalling dlerror\033[0m\n" -ex "call ((char*(*)(void))dlerror)()" -ex "detach" -ex "quit"
`

**Closed** 2021-02-11 21:19 UTC
Labels: crash, not our bug, p:high

**Comment by TotallyNotElite** [comment] 2021-02-11 21:25
"Pulling" is not enough, please use the intended mechanisms for updating cathook.

**Comment by iraizo** [comment] 2021-02-11 21:25
> "Pulling" is not enough, please use the intended mechanisms for updating cathook.

my bad
