### ISSUE TITLE
Unable to Compile Correctly: XBPS Dependencies

### ISSUE THREAD

**Issue by daggerfella** [nullworks/cathook#1075] opened 2020-07-27 09:21 UTC
**Note**
I do realize that you might not be able to help since Void Linux and XBPS package manager are uncommon and unsupported.

Distribution: Void Linux
Package Manager: XBPS
XBPS Packages: _git, boost, cmake, make, gcc, gdb, SDL2-32bit, glew-32bit, glew-devel, freetype-32bit, rsync, libglvnd-32bit, dialog_
Arch Packages: _git boost cmake make gcc gdb lib32-sdl2 lib32-glew lib32-freetype2 rsync lib32-libglvnd dialog_

**Logs**
Compilation had no errors until it was about to finish:
`/bin/ld: /usr/lib/libfreetype.so: error adding symbols: file in wrong format`
This is easy to understand, i installed multilib versions of freetype.

After that i got this error while it was building CMakeFiles/cathook.dir/src/hooks/CreateMove.cpp.o:
```
In file included from /home/user/cathook/include/conditions.hpp:12,
                 from /home/user/cathook/include/helpers.hpp:27,
                 from /home/user/cathook/include/common.hpp:50,
                 from /home/user/cathook/build/CMakeFiles/cathook.dir/cmake_pch.hxx:5,
                 from <command-line>:
/home/user/cathook/src/hooks/CreateMove.cpp: In function 'bool hooked_methods::methods::CreateMove(void*, float, CUserCmd*)':
/home/user/cathook/src/hooks/CreateMove.cpp:130:5:   in 'constexpr' expansion of 'IsTF2C()'
/home/user/cathook/include/gameinfo.hpp:23:21:   in 'constexpr' expansion of 'c_strcmp(((const char*)"tf2"), ((const char*)"tf2c"))'
/home/user/cathook/src/hooks/CreateMove.cpp:130:5: error: modification of '#'result_decl' not supported by dump_expr#<expression error>' is not a constant expression
  130 |     IF_GAME(IsTF2C())
      |     ^~~~~~~
/home/user/cathook/src/hooks/CreateMove.cpp:130: confused by earlier errors, bailing out
make[3]: *** [CMakeFiles/cathook.dir/build.make:1659: CMakeFiles/cathook.dir/src/hooks/CreateMove.cpp.o] Error 1
make[3]: *** Waiting for unfinished jobs....
make[2]: *** [CMakeFiles/Makefile2:774: CMakeFiles/cathook.dir/all] Error 2
make[1]: *** [CMakeFiles/Makefile2:781: CMakeFiles/cathook.dir/rule] Error 2
make: *** [Makefile:197: cathook] Error 2
```
And after removing 32bit packages of freetype to test again:
```
make[3]: *** No rule to make target '/usr/lib32/libfreetype.so', needed by 'bin/libcathook.so'. Stopped.
make[3]: *** Waiting for unfinished jobs....
make[2]: *** [CMakeFiles/Makefile2:774: CMakeFiles/cathook.dir/all] Error 2
make[1]: *** [CMakeFiles/Makefile2:781: CMakeFiles/cathook.dir/rule] Error 2
make: *** [Makefile:197: cathook] Error 2

Failed to compile cathook
```
Which is expected but also quite weird considering that compilation went quite well until it was almost done the first time.

Occasionally it wouldn't give any errors until the very end:

```
/bin/ld: /usr/lib/libSDL2.so: error adding symbols: file in wrong format
collect2: error: ld returned 1 exit status
make[3]: *** [CMakeFiles/cathook.dir/build.make:3151: bin/libcathook.so] Error 1
make[2]: *** [CMakeFiles/Makefile2:774: CMakeFiles/cathook.dir/all] Error 2
make[1]: *** [CMakeFiles/Makefile2:781: CMakeFiles/cathook.dir/rule] Error 2
make: *** [Makefile:197: cathook] Error 2

Failed to compile cathook
```
Even if both 32bit and 64bit packages of SDL2 were installed.

**Additional context**
You can use https://voidlinux.org/packages/ to search packages. I will give feedback in comments if i manage to fix it or find additional information.

**Comment by lbaldim** [comment] 2020-07-27 09:30
Turns out i had both SDL2-devel and SDL2-32bit installed so it wasn't using the 32bit version. So i uninstalled the SDL2-devel package:
```
make[3]: *** No rule to make target '/usr/lib/libSDL2main.a', needed by 'bin/libcathook.so'. Stopped.
make[2]: *** [CMakeFiles/Makefile2:774: CMakeFiles/cathook.dir/all] Error 2
make[1]: *** [CMakeFiles/Makefile2:781: CMakeFiles/cathook.dir/rule] Error 2
make: *** [Makefile:197: cathook] Error 2
```
I installed SDL2-devel back just to check if anything changed:
```
/bin/ld: /usr/lib/libSDL2.so: error adding symbols: file in wrong format
collect2: error: ld returned 1 exit status
make[3]: *** [CMakeFiles/cathook.dir/build.make:3151: bin/libcathook.so] Error 1
make[2]: *** [CMakeFiles/Makefile2:774: CMakeFiles/cathook.dir/all] Error 2
make[1]: *** [CMakeFiles/Makefile2:781: CMakeFiles/cathook.dir/rule] Error 2
make: *** [Makefile:197: cathook] Error 2
```
I guess it's normal but i still don't understand why it worked before and compilations are so inconsistent.

**Comment by BenCat07** [comment] 2020-07-27 09:37
Cmake tries to find the libraries but it can't

**Comment by lbaldim** [comment] 2020-07-27 09:38
If you are talking about the second log, i do believe that it's fixed. I have no idea how or why though. It seems like SDL2 is the only problem right now.

**Comment by lbaldim** [comment] 2020-07-27 09:41
Okay, it seems like devel and 32bit are both needed so i'll try installing the SDL2-devel-32bit package. My compilations take extremely long so i'll report back in an hour or two.

**Comment by lbaldim** [comment] 2020-07-27 10:01
Update: It managed to compile once but it doesn't the second time so i can't inject really. I'm now getting the same error:
```
In file included from /home/user/cathook/include/conditions.hpp:12,
                 from /home/user/cathook/include/helpers.hpp:27,
                 from /home/user/cathook/include/common.hpp:50,
                 from /home/user/cathook/build/CMakeFiles/cathook.dir/cmake_pch.hxx:5,
                 from <command-line>:
/home/user/cathook/src/hooks/CreateMove.cpp: In function 'bool hooked_methods::methods::CreateMove(void*, float, CUserCmd*)':
/home/user/cathook/src/hooks/CreateMove.cpp:130:5:   in 'constexpr' expansion of 'IsTF2C()'
/home/user/cathook/include/gameinfo.hpp:23:21:   in 'constexpr' expansion of 'c_strcmp(((const char*)"tf2"), ((const char*)"tf2c"))'
/home/user/cathook/src/hooks/CreateMove.cpp:130:5: error: modification of '#'result_decl' not supported by dump_expr#<expression error>' is not a constant expression
  130 |     IF_GAME(IsTF2C())
      |     ^~~~~~~
/home/user/cathook/src/hooks/CreateMove.cpp:130: confused by earlier errors, bailing out
make[3]: *** [CMakeFiles/cathook.dir/build.make:1659: CMakeFiles/cathook.dir/src/hooks/CreateMove.cpp.o] Error 1
make[3]: *** Waiting for unfinished jobs....
make[2]: *** [CMakeFiles/Makefile2:774: CMakeFiles/cathook.dir/all] Error 2
make[1]: *** [CMakeFiles/Makefile2:781: CMakeFiles/cathook.dir/rule] Error 2
make: *** [Makefile:197: cathook] Error 2
```
I can't read it so i don't know what to do really. Most importantly, i still don't understand why it's so inconsistent.

**Comment by BenCat07** [comment] 2020-07-27 10:15
this is a bug caused by gcc 9.3.0, it's rather random and why it happens, noone knows

**Comment by lbaldim** [comment] 2020-07-27 10:26
> this is a bug caused by gcc 9.3.0, it's rather random and why it happens, noone knows

What should i do then? Downgrade?

**Comment by BenCat07** [comment] 2020-07-27 10:28
It randomly appears/disappears on versions with the issue.
 i don't know if the issue exists in previous versions, besides 8.9.0 where it exists for sure, and newer versions do not have the bug. So either you find a working version that is above 8.9.0 or you use a newer gcc

**Comment by BenCat07** [comment] 2020-07-27 10:28
Or you can keep using 9.3.0 and remove and readd the build folder until it works :shrug:

**Comment by lbaldim** [comment] 2020-07-27 10:34
> So either you find a working version that is above 8.9.0 or you use a newer gcc

You mean above 9.3.0 or that 9.3.0 is the only version that is above 8.9.0 and has the bug?

**Comment by lbaldim** [comment] 2020-07-27 10:37
Alright, i'll give it a shot and report back.

**Comment by BenCat07** [comment] 2020-11-01 09:08
Yeah that works but who knows if gcc6 will be outdated for us in the future

**Comment by RaphyJake** [comment] 2020-11-01 09:59
Removing build folder and attempting again works indeed! I reckon you should also be able to just use gcc6 to compile it, which is present in void's repos. I think you can close this, I can edit the install script to include void linux and send a pull request if you want to.

**Closed** 2021-03-30 05:00 UTC
Labels: enhancement, help wanted
