### ISSUE TITLE
Engi bots are broken

### ISSUE THREAD

**Issue by EngineerGaming69** [nullworks/cathook#1145] opened 2020-10-27 20:04 UTC
Describe the Bug
Engi bots like to walk past there buildings and stand still when they go to upgrade or repair them but never do it.
Expected behavior
The engi bots should not stop trying to find there buildings until they are able to hit them.

**Comment by BenCat07** [comment] 2020-10-27 20:06
The issue is them not walking close enough

**Comment by BenCat07** [comment] 2020-10-27 20:06
This will be fixed with the navbot rewrite i will be working on on the weekends

**Comment by EngineerGaming69** [comment] 2020-10-27 20:06
but when i push them closer they start to upgrade

**Comment by BenCat07** [comment] 2020-10-27 21:46
I'm aware

**Comment by EngineerGaming69** [comment] 2020-11-02 00:32
have you started fixing this yet? The sentry aimbot fix really didnt do anything for this

**Comment by BenCat07** [comment] 2020-11-02 07:15
I told you i am remaking navbot

**Comment by iraizo** [comment] 2021-03-28 20:25
Again not sure if this issue still persists

**Comment by BenCat07** [comment] 2021-03-28 20:48
engineer bots are no longer in the code due to the complexity needed to make them work

**Closed** 2021-03-28 20:53 UTC
Labels: bug
