### ISSUE TITLE
Quality of Life: make zoomed sensetivity match normal sensitivity when using Custom FOV

### ISSUE THREAD

**Issue by buyBread** [nullworks/cathook#1084] opened 2020-08-13 22:59 UTC
It's distracting and quite annoying to suddenly have your sensitivity become extremely low. I am pretty much always forced to set the `zoom_sensitivity_ratio` convar to the same value as my `sensitivity` value. It would be nice if this was automated while using Custom FOV.

**Comment by SylveonBottle** [comment] 2020-08-16 23:11
I agree that this should've been something that nozoom already does, but- simple solution: put the zoom command in autoexec? Or maybe bind it to the same button as aimbot

**Comment by BenCat07** [comment] 2020-10-09 18:17
Duplicate of #958.

**Closed by BenCat07** 2020-10-09 18:17 UTC
