### ISSUE TITLE
Two new suggestions

### ISSUE THREAD

**Issue by Auditormadness9** [nullworks/cathook#1372] opened 2021-03-08 10:41 UTC
- [ ] 1. Auto kick people I stole name from.
- [ ] 2. Auto cat_mm_abandon when auto-balanced.

**Comment by explowz** [comment] 2021-03-08 20:40
1. Yeah makes sense.
2. Makes no sense. Why would you want to do that?

**Comment by BenCat07** [comment] 2021-03-08 21:26
2. is meant for when you make a party

**Comment by iraizo** [comment] 2021-03-28 20:00
Duplicate of https://github.com/nullworks/cathook/issues/1167

**Closed by iraizo** 2021-03-28 20:00 UTC
Labels: duplicate, feature suggestion
