### ISSUE TITLE
Nice sdk knowledge

### ISSUE THREAD

**Issue by clowcheck** [nullworks/cathook#1339] opened 2021-02-02 21:05 UTC
Take a look at this commit, hopefully someone fixed it. Do you guys even know what a get_max_client is?

cathook/src/helpers.cpp

Line 732 in 33de377

 void VectorTransform(const float *in1, const matrix3x4_t &in2, float *out) 
-> why is VectorTransform is here excuse me? isn't this supposed to be somewhere in math cpp?
if (CE_GOOD(wep)) { weapon_mode = GetWeaponModeloc(); if (wep->m_iClassID() == CL_CLASS(CTFSniperRifle) || wep->m_iClassID() == CL_CLASS(CTFSniperRifleDecap)) holding_sniper_rifle = true; else if (wep->m_iClassID() == CL_CLASS(CTFWeaponBuilder) || wep->m_iClassID() == CL_CLASS(CTFWeaponSapper)) holding_sapper = true; else if (wep->m_iClassID() == CL_CLASS(CTFMinigun)) { if (CE_INT(LOCAL_W, netvar.iWeaponState) == 2 || CE_INT(LOCAL_W, netvar.iWeaponState) == 1) bRevving = true; else if (CE_INT(LOCAL_W, netvar.iWeaponState) == 3) bRevved = true; } // Detect when a melee hit will result in damage, useful for aimbot and antiaim if (CE_FLOAT(wep, netvar.flNextPrimaryAttack) > g_GlobalVars->curtime && weapon_mode == weapon_melee) { if (melee_damagetick == tickcount) { weapon_melee_damage_tick = true; melee_damagetick = ULONG_MAX; } else if (bAttackLastTick && (long long) melee_damagetick - (long long) tickcount < 0) // Thirteen ticks after attack detection = damage tick melee_damagetick = tickcount + TIME_TO_TICKS(0.195f); } else melee_damagetick = 0; } team = CE_INT(entity, netvar.iTeamNum); life_state = CE_BYTE(entity, netvar.iLifeState); v_ViewOffset = CE_VECTOR(entity, netvar.vViewOffset); v_Origin = entity->m_vecOrigin(); v_OrigViewangles = current_user_cmd->viewangles; v_Eye = v_Origin + v_ViewOffset; clazz = CE_INT(entity, netvar.iClass); health = CE_INT(entity, netvar.iHealth); this->bUseSilentAngles = false; bZoomed = HasCondition<TFCond_Zoomed>(entity); if (bZoomed) { if (flZoomBegin == 0.0f) flZoomBegin = g_GlobalVars->curtime; }

nice coding style are you guys after YandereDev?

`bool trace::FilterNavigation::ShouldHitEntity(IHandleEntity *handle, int mask)
{
IClientEntity *entity;
ClientClass *clazz;

if (!handle)
    return false;
entity = (IClientEntity *) handle;
clazz  = entity->GetClientClass();

// Ignore everything that is not the world or a CBaseEntity
if (entity->entindex() != 0 && clazz->m_ClassID != CL_CLASS(CBaseEntity))
{
    // Besides respawn room areas, we want to explicitly ignore those if they are not on our team
    if (clazz->m_ClassID == CL_CLASS(CFuncRespawnRoomVisualizer))
        if (CE_GOOD(LOCAL_E) && (g_pLocalPlayer->team == TEAM_RED || g_pLocalPlayer->team == TEAM_BLU))
        {
            // If we can't collide, hit it
            if (!re::C_BaseEntity::ShouldCollide(entity, MOVEMENT_COLLISION_GROUP, g_pLocalPlayer->team == TEAM_RED ? RED_CONTENTS_MASK : BLU_CONTENTS_MASK))
                return true;
        }
    return false;
}
return true;
}`

wow will there be another useless "if" after your guys next commit?

/* Do not hit yourself. Idiot. */ if (entity == m_pSelf) return false; if (entity == m_pIgnoreFirst) return false;

wowwwww i haven't seen smh like this before maybe use "||"....... i can actually teach you guys C++ logical operators if you want. but anyways next codee..

` if (yDelta_a == 0)
{
Center.x = AB_Mid.x;

    if (xDelta_b == 0)
        return std::nullopt;
    else
    {
        Center.y = BC_Mid.y + (BC_Mid.x - Center.x) / bSlope;
    }
}
else if (yDelta_b == 0)
{
    Center.x = BC_Mid.x;
    if (xDelta_a == 0)
        return std::nullopt;
    else
        Center.y = AB_Mid.y + (AB_Mid.x - Center.x) / aSlope;
}
else if (xDelta_a == 0)
    return std::nullopt;
else if (xDelta_b == 0)
    return std::nullopt;
else
{
    Center.x = (aSlope * bSlope * (AB_Mid.y - BC_Mid.y) - aSlope * BC_Mid.x + bSlope * AB_Mid.x) / (bSlope - aSlope);
    Center.y = AB_Mid.y - (Center.x - AB_Mid.x) / aSlope;
}`
WHAT THE ACTUAL FUCK IS THIS LMAO?

https://github.com/nullworks/cathook/blob/master/src/hooks/RunCommand.cpp
WOOOWW premium RunCommand mentally challanged coders on the job!! i haven't seen a perfect RunCommand like this before. It is amazing keep it up!!

**Comment by TotallyNotElite** [comment] 2021-02-02 21:14
Duplicate of #1337

**Closed by TotallyNotElite** 2021-02-02 21:14 UTC
