### ISSUE TITLE
I cant attach cathook to my TF2

### ISSUE THREAD

**Issue by AWSDZXC** [nullworks/cathook#1488] opened 2021-06-15 09:29 UTC
When i open tf2 and pressing Attach i see this
/usr/bin/bash: line 0: cd: too many arguments
/usr/bin/bash: . / attach: No such file or directory

**Comment by Zanthed** [comment] 2021-06-17 00:14
@AWSDZXC Please follow the bug report template so we can properly assist you. Two lines of output tells us nothing.

Also, how are you attaching? Script or GUI?

```
## System Information
**OS:**  
**DE:**  
**Cathook Version:**  

## Config used
<!-- Add the .conf file you were using from /opt/cathook/data/configs/. -->
<!-- Drag and drop the file here. -->
<!-- You can delete this line if you don't have any crash reports to give. -->


## Logs / Crash Report  
<!-- Add logs from /tmp/. if it crashes, paste symbolize-crash-log here. -->
<!-- Drag and drop the file here. -->
<!-- You can delete this line if you don't have any crash reports to give. -->

## Description  
<!-- Please provide a clear and concise description of what the bug is. -->

## Steps to reproduce  
- [ ] I am able to consistently reproduce this error
<!-- If you can consistently get this error, let us know how! If we can reproduce it, we can fix it. If we can't, then we're just shooting in the dark on whether or not we've fixed it! -->

Steps to reproduce the behavior:  
<!-- Example only, please delete these steps and enter your own. -->
1. Enable X
2. Do Y
3. Notice Z

## Additional context 
<!-- Is there anything specific else that we should know that could help us find/fix this bug? -->

## Screenshot of cheats enabled  
<!-- Even if you don't think it could effect what happened, sometimes some cheats may break others. We don't know! We may never know, if you don't show us what cheats are enabled. -->


## Checklist  
- [ ] I have included my DE, WM, and version of Cathook.
- [ ] I have included the steps to reproduce and my logs to the best I am able to share.
- [ ] The Developers are allowed to contact me on [the official telegram](https://t.me/nullworks) for further information if they need to. (Put your username here)
```

**Comment by AWSDZXC** [comment] 2021-06-19 11:17
## System Information
**OS:Linux**  
**DE:Gnome**  
**Cathook Version:Latest**  

## Config used
Any

## Logs / Crash Report  
none

## Description  
I downloaded a Cathook binary file,extracted,opened,pressed update button and wait for finish, then i opened TF2 and pressed Alt+Tab to get back, pressed Attach button and then i saw this
/usr/bin/bash: line 0: cd: too many arguments
/usr/bin/bash: . / attach: No such file or directory

## Steps to reproduce  
- [yes ] I am able to consistently reproduce this error


Steps to reproduce the behavior:  
1. Install binary file
2. extract him
3. open
4. press update
5. open your TF2
6. get back with alt+tab 
7. press Attach
8. see this*screenshot*
![Снимок экрана от 2021-06-19 17-04-34](https://user-images.githubusercontent.com/85932707/122640234-18718080-d107-11eb-9f87-4841a3c93e7e.png)
Screenshot text:/
usr/bin/bash: line 0: cd: too many arguments
/usr/bin/bash: . / attach: No such file or directory


## Additional context 
Sadly no

## Screenshot of cheats enabled  
I cant enable cheats without attached cathook
## Checklist  
- [yes] I have included my DE, WM, and version of Cathook.
- [yes ] I have included the steps to reproduce and my logs to the best I am able to share.
- [yes ] The Developers are allowed to contact me on [the official telegram](https://t.me/nullworks) for further information if they need to. (Yagivkyokavaliwik)

**Comment by BenCat07** [comment] 2021-06-19 11:22
This seems to have been caused by a space in your file path, will be working on a fix. in teh meantime, move the GUI to a path without a space in it.

**Comment by AWSDZXC** [comment] 2021-06-21 14:45
*move the GUI to a path without a space in it.*
Can you please say how to do it?

**Comment by Zanthed** [comment] 2021-06-21 22:54
> _move the GUI to a path without a space in it._
> Can you please say how to do it?
@AWSDZXC 

Say your absolute path to the GUI AppImage is `/home/user/Cat Hook/Cathook.AppImage`
You need to move it to a different directory where the absolute path has no spaces in it.

For example: `/home/user/cathook/Cathook.AppImage`

**Comment by iraizo** [comment] 2021-06-23 21:11
Actually should be fixed.

**Comment by AWSDZXC** [comment] 2021-06-25 09:44
Many thanks i attached!

**Comment by iraizo** [comment] 2021-06-25 10:59
im not sure what you mean by reopend, if you didnt close TF2 you can press `insert` to open it.

**Comment by AWSDZXC** [comment] 2021-06-26 17:54
Also i must say that i installed cathook through terminal and i closed tf2 then i opened and insert key not working

**Comment by BenCat07** [comment] 2021-06-26 18:08
tf2 needs to be running, press attach while it is

**Comment by AWSDZXC** [comment] 2021-06-27 08:40
I attached successfully once i saw hack menu, then i exit from terminal and closed tf2, opened again and insert key doesnt work

**Comment by iraizo** [comment] 2021-06-27 11:18
you cant close tf2, you need to reinject if you do so

**Closed** 2021-07-14 20:08 UTC
Labels: bug, enhancement
