### ISSUE TITLE
Fake angles fix?

### ISSUE THREAD

**Issue by acuifex** [nullworks/cathook#702] opened 2019-03-16 01:39 UTC
**Describe the Bug**
When you toggle fake angles it shows only real angle (sorry for my bad english i'm from somali)

**To Reproduce**
1. Open menu on Insert
2. Get in hvh tab
3. Set yaw to any fake angle
4. ???
5. PROFIT

**Expected behavior**
Show fake angles

**Screenshots**

**Logs**
Add logs from /tmp/ and  - if it crashes - use symbolize-crash-log here.
https://drive.google.com/file/d/16b1nrHebKIM8UngYNS6mklYL5DmuqJ1i/view?usp=sharing

**Additional context**

**Comment by TotallyNotElite** [comment] 2019-03-16 01:59
If you have visual.thirdperson.real-angles enabled, you will see real angles in thirdperson. Fake angles are only visible to other players.

**Comment by acuifex** [comment] 2019-03-16 10:08
I mean fake angles don't show up at all

**Comment by BenCat07** [comment] 2019-03-16 10:12
Yes it only shows the real angles so you can actually tell what is going on. i am adding an option for showing both i guess.

**Comment by BenCat07** [comment] 2019-03-16 10:14
Others cannot see the fake angles obviously

**Comment by acuifex** [comment] 2019-03-16 10:18
I think you don't understand me right, Enemies, Team and me see only real angle, no fakes

**Comment by BenCat07** [comment] 2019-03-16 10:21
then you didn't set misc.fakelag.

**Comment by acuifex** [comment] 2019-03-16 10:21
Okay, thank you i will test

**Comment by acuifex** [comment] 2019-03-17 15:50
Reopen issue please. have same issue with fakelag 
P.S. i had no time to test your fix

**Comment by TotallyNotElite** [comment] 2019-03-17 15:51
@acuifex We tested it yesterday. I had fake up on and others saw me looking upwards.

**Comment by BenCat07** [comment] 2019-03-17 15:52
I used AntiAim today. It works fine if you have misc.fakelag set, you see the same on your end that others do, but your angles are actually different.

**Comment by BenCat07** [comment] 2019-03-17 15:52
If you use a bad pitch your hitboxes eill overlay and Fake yaw will be useless

**Comment by acuifex** [comment] 2019-03-17 15:54
You mean in third person with show real angles you see fakes?

**Comment by TotallyNotElite** [comment] 2019-03-17 15:55
> You mean in third person with show real angles you see fakes?

No. Idk what @BenCat07 was talking about but you definitely do not see fake angles in thirdperson. They are only visible to other players.

**Comment by acuifex** [comment] 2019-03-17 15:58
But my friend see same angles that i see in thirdperson, tested with fakeoffset

**Comment by acuifex** [comment] 2019-03-17 16:16
Any help with yaw? pitch work fine

**Comment by acuifex** [comment] 2019-03-17 16:30
i think bSendPackets dosen't work. Because fake crouch don't work too

**Comment by BenCat07** [comment] 2019-03-17 16:39
Nope found the issue

**Comment by BenCat07** [comment] 2019-03-17 16:39
1. Visuals are inaccurate
2. For some reason fake right/left are having issues

**Comment by TotallyNotElite** [comment] 2019-03-17 16:40
Turns out antiaim is broken. Thanks for the report @acuifex.

**Comment by acuifex** [comment] 2019-03-17 16:42
Okay, Thank you for understanding! :-) i hope you will fix

**Comment by BenCat07** [comment] 2019-03-17 16:43
Fake crouch was just debug Code, it doesn't work and i am unsure when and why it landed on the master branch

**Comment by acuifex** [comment] 2019-03-17 16:44
Work on fix please. don't talk to me XD

**Comment by acuifex** [comment] 2019-03-18 21:07
Every thing working properly now. Closing the issue

**Comment by BenCat07** [comment] 2019-03-18 21:12
Fake angles are confusing ad hell imo

**Comment by acuifex** [comment] 2019-03-18 21:45
You still not finished? ok i will open. just close when you done

**Comment by BenCat07** [comment] 2019-03-18 21:55
No it's done just the issue was mostly caused by my own confusion over fakes that's all

**Closed by BenCat07** 2019-03-18 21:55 UTC
Labels: bug, p:high
